enabled_rules:
    - anyobject_protocol
    - array_init
    - attributes
    - block_based_kvo
    - class_delegate_protocol
    - closing_brace
    - closure_body_length
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon
    - comma
    - contains_over_first_not_nil
    - control_statement
    - custom_rules
    - discarded_notification_center_observer
    - discouraged_direct_init
    - discouraged_object_literal
    - dynamic_inline
    - empty_count
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - empty_string
    - empty_xctest_method
    - explicit_self
    - fatal_error_message
    - first_where
    - force_cast
    - force_try
    - for_where
    - identifier_name
    - identical_operands
    - implicit_getter
    - implicit_return
    - implicitly_unwrapped_optional
    - inert_defer
    - is_disjoint
    - joined_default_parameter
    - generic_type_name
    - large_tuple
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_nsgeometry_functions
    - legacy_random
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - mark
    - multiline_arguments
    - multiline_function_chains
    - multiline_parameters
    - nimble_operator
    - nesting
    - notification_center_detachment
    - opening_brace
    - operator_usage_whitespace
    - operator_whitespace
    - object_literal
    - overridden_super_call
    - override_in_extension
    - private_action
    - private_outlet
    - private_over_fileprivate
    - private_unit_test
    - prohibited_super_call
    - protocol_property_accessors_order
    - redundant_discardable_let
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_set_access_control
    - redundant_string_enum_value
    - redundant_nil_coalescing
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - single_test_class
    - statement_position
    - static_operator
    - sorted_first_last
    - sorted_imports
    - superfluous_disable_command
    - switch_case_alignment
    - switch_case_on_newline
    - toggle_bool
    - trailing_closure
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - todo
    - type_name
    - unneeded_break_in_switch
    - unused_enumerated
    - unused_import
    - unneeded_parentheses_in_closure_argument
    - unused_optional_binding
    - unused_closure_parameter
    - valid_ibinspectable
    - vertical_whitespace
    - weak_delegate
    - void_return
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - xctfail_message
    - yoda_condition
disabled_rules:
    - compiler_protocol_init
    - conditional_returns_on_newline
    - convenience_type
    - cyclomatic_complexity # counts ifs
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - explicit_acl # All declarations should specify Access Control Level keywords explicitly.
    - explicit_enum_raw_value
    - explicit_init
    - explicit_top_level_acl
    - explicit_type_interface
    - extension_access_modifier
    - fallthrough
    - file_header
    - file_length # I like this but not now
    - file_name
    - force_unwrapping
    - function_body_length
    - function_default_parameter_at_end
    - function_parameter_count
    - let_var_whitespace
    - line_length
    - missing_docs
    - modifier_order
    - multiline_arguments_brackets
    - multiline_literal_brackets
    - multiline_parameters_brackets
    - multiple_closures_with_trailing_closure
    - nimble_operator
    - no_extension_access_modifier
    - no_fallthrough_only
    - no_grouping_extension
    - number_separator
    - pattern_matching_keywords
    - prefixed_toplevel_constant
    - prohibited_interface_builder
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - redundant_type_annotation
    - required_enum_case
    - strict_fileprivate
    - syntactic_sugar
    - type_body_length
    - unavailable_function
    - untyped_error_in_catch
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
trailing_whitespace:
    ignores_empty_lines: true
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
