language: objective-c
osx_image: xcode8.3
xcode_workspace: hat-mobile-ios.xcworkspace
xcode_scheme: hat-mobile-ios
xcode_sdk: iphonesimulator10.3
before_install:
   - rvm use system
   - sudo gem install cocoapods
script: xcodebuild clean build -workspace hat-mobile-ios/hat-mobile-ios.xcworkspace -scheme hat-mobile-ios -destination 'platform=iOS Simulator,name=iPhone 7'