language: objective-c
osx_image: xcode10.1
xcode_workspace: HAT.xcworkspace
xcode_scheme: HAT
xcode_sdk: iphonesimulator12
before_install:
   - rvm use system
   - sudo gem install cocoapods
script: xcodebuild build test -workspace HAT.xcworkspace -scheme HAT -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone X'