language: objective-c
osx_image: xcode9
xcode_workspace: HAT.xcworkspace
xcode_scheme: HAT
xcode_sdk: iphonesimulator11
before_install:
   - rvm use system
   - sudo gem install cocoapods
script: xcodebuild build test -workspace HAT.xcworkspace -scheme HAT -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 8'