language: objective-c
osx_image: xcode10.2
xcode_workspace: HAT.xcworkspace
xcode_scheme: HAT
xcode_sdk: iphonesimulator12.2
before_install:
   - rvm use system
   - sudo gem install cocoapods
script: xcodebuild build test -workspace HAT.xcworkspace -scheme HAT -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X'
