name: Build and test HAT API iOS

on: push

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bundle Install
        run: bundle install
      - name: Build and test
        run: bundle exec fastlane test
      - name: Lint CocoaPod file
        run: pod lib lint --skip-tests --allow-warnings
