name: Release HAT API iOS

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bundle Install
        run: bundle install
      - name: Build and test
        run: bundle exec fastlane test
      - name: Lint CocoaPod file
        run: pod lib lint --skip-tests --allow-warnings
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push HAT-API-for-iOS.podspec
